---
# Example webhook Notification Channel for development environment
apiVersion: openchoreo.dev/v1alpha1
kind: ObservabilityAlertsNotificationChannel
metadata:
  name: webhook-notification-channel-development
  namespace: default
spec:
  environment: development
  type: webhook
  webhookConfig:
    url: https://webhook.acme.com  # Replace with your webhook URL
    headers:
      Content-Type:
        value: "application/json"
      # Custom header for webhook authentication (if required)
      X-API-Key:
        valueFrom:
          secretKeyRef:
            name: webhook-notification-channel-development-webhook-auth
            key: api-key
    # Optional: Payload template using CEL expressions (${...})
    # If not provided, the raw alertDetails object will be sent as JSON
    # For Slack, use the template below. For other webhooks, customize as needed.
    payloadTemplate: |
      {
        "text": "Alert: ${alertName}",
        "blocks": [
          {
            "type": "header",
            "text": {
              "type": "plain_text",
              "text": "🚨 OpenChoreo Alert: ${alertName}"
            }
          },
          {
            "type": "section",
            "fields": [
              {
                "type": "mrkdwn",
                "text": "*Severity:*\n${alertSeverity}"
              },
              {
                "type": "mrkdwn",
                "text": "*Value:*\n${alertValue}"
              },
              {
                "type": "mrkdwn",
                "text": "*Threshold:*\n${alertThreshold}"
              },
              {
                "type": "mrkdwn",
                "text": "*Component:*\n${component}"
              }
            ]
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*Description:*\n${alertDescription}"
            }
          },
          {
            "type": "context",
            "elements": [
              {
                "type": "mrkdwn",
                "text": "Project: ${project} | Environment: ${environment} | Time: ${alertTimestamp}"
              }
            ]
          }
        ]
      }

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-notification-channel-development-webhook-auth
  namespace: default
type: Opaque
stringData:
  api-key: webhook-api-key    # Replace with your webhook API key
