apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo

  componentType: deployment/service
  autoDeploy: true

  parameters:
    replicas: 1
    port: 8080
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"

  # Attach alert rule as a trait
  traits:
    - name: observability-alert-rule
      instanceName: recommendation-high-cpu-alert
      parameters:
        description: "Alert when recommendationservice CPU usage is greater than 80% for last 5 minutes"
        severity: "critical"
        source:
          type: "metric"
          # Logical metric name interpreted by the observability backend
          metric: "cpu_usage"
        condition:
          window: "1m"
          interval: "1m"
          operator: "gt"
          threshold: 80

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: recommendation
  namespace: default
spec:
  owner:
    componentName: recommendation
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "8080"
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog:80"
